<!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">-->
<style>
    .form-inline label,
    .form-label {
        display: inline-block;
        font-size: .8em;
    }
    .btn {
        border-radius: 3px;
        background-color: white;
        border-color: lightgray;
    }
    h4 .btn {
        vertical-align: inherit;
    }
    .harvard-table {
        width: 100%;
    }
    .harvard-table thead td {
        padding-right: 8px;
        padding-bottom: 8px;
    }
    .harvard-table thead tr {
        vertical-align: bottom;
    }
    .harvard-table tbody td {
        padding: 5px 0px;
        padding-left: 9px;
    }
    section {
        background-color: #f8f8f8;
        padding: 10px 20px;
        margin-bottom: 20px;
        border: solid 1px #e8e8e8;
        border-radius: 3px;
    }

</style>
