<?php
/**
 * Created by PhpStorm.
 * User: mike
 * Date: 2016-03-13
 * Time: 4:12 PM
 */
echo $this->partial('style.phtml');
echo $this->renderTabs($this->tabs);
?>

<form method="post" class="list">
<table class="harvard-table">
    <?php

    if( empty($this->blockedDomains) ) {
        echo "<tr><td>{$this->lmsg('no-domains-blocked')}</td></tr>";
    }
    else {
        foreach ($this->blockedDomains as $blocked) {
            $domain = $blocked['domain'];
            $id = $blocked['id'];
            $reason = $blocked['reason'];
            echo "<tr><td><a href='/smb/mail-settings/edit/id/$id/domainId/$id'>$domain</a></td>";
            echo "<td>$reason</td>";
            echo "<td><button class='btn btn-default' type='submit' name='unblock' value='$domain'>{$this->lmsg('enable-domain-button')}</button>";
        }
    }

    ?>

</table>
</form>


