<?php
/**
 * Created by PhpStorm.
 * User: mike
 * Date: 2016-03-13
 * Time: 4:00 PM
 */

echo $this->renderTabs($this->tabs);

// TODO: Can we use the URL helper?
$entryPoint  = !empty($_SERVER['REQUEST_SCHEME']) ? $_SERVER['REQUEST_SCHEME'] : 'http';
$entryPoint .= '://' . $_SERVER['HTTP_HOST'];
$entryPoint .=  '/modules/harvard/public/index.php';
$entryPoint .= '?auth_token=' . $this->token;

?>

<!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">-->
<style>
    .form-inline label {
        display: inline-block;
    }
    .btn {
        border-radius: 3px;
        background-color: white;
        border-color: lightgray;
    }
    .btn-xs {
        height: 0.9em;
    }
</style>

<h3>API Key</h3>
<form class="form-horizontal" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'genkey')); ?>">
    <div class="form-group">
        <label for="api-key">API Key:</label>

        <input type="text" readonly size="40" name="token" value="<?php echo $this->token; ?>" id="api-key"/>
        <button type="submit" class="btn input-group-addon">Generate</button>
    </div>
    <div class="form-group">
        <label for="api-key">Entry point:</label>

        <input type="text" readonly size="60" name="token" value="<?php echo $entryPoint; ?>" id="api-key"/>
    </div>
</form>

<hr/>
<h3>Add Action</h3>
<div class="form-inline">
    <label>
        <small>Event</small>
        <br/>
        <select>
            <option>All Events</option>
            <option>Domain is sending Spam</option>
            <option>Domain is sending to invalid recipients</option>
            <option>Domain is generating complaints from receivers</option>
        </select>
    </label>
    <label>
        <small>Action</small>
        <br/>
        <select>
            <option>Throttle Sender</option>
            <option>Throttle Domain</option>
            <option>Block Sender</option>
            <option>Block Domain</option>
        </select>
    </label>
    <button class="btn btn-default btn-xs">Add</button>
</div>
