<?php
/**
 * Created by PhpStorm.
 * User: mike
 * Date: 2016-03-13
 * Time: 4:00 PM
 */

echo $this->renderTabs($this->tabs);

// TODO: Can we use the URL helper?
$entryPoint  = !empty($_SERVER['REQUEST_SCHEME']) ? $_SERVER['REQUEST_SCHEME'] : 'http';
$entryPoint .= '://' . $_SERVER['HTTP_HOST'];
$entryPoint .=  '/modules/harvard/public/index.php';
$entryPoint .= '?auth_token=' . $this->token;

?>

<!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">-->
<style>
    .form-inline label {
        display: inline-block;
    }
    .btn {
        border-radius: 3px;
        background-color: white;
        border-color: lightgray;
    }
    thead td {
        padding-right: 8px;
        padding-bottom: 8px;
    }
    thead tr {
        vertical-align: bottom;
    }
    tbody td {
        padding: 5px 0px;
        padding-left: 9px;
    }
    section {
        background-color: #f8f8f8;
        padding: 10px 20px;
        margin-bottom: 10px;
        border: solid 1px #e8e8e8;
        border-radius: 3px;
    }

</style>
<h3>API Settings</h3>
<section>
    <form method="post" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'genkey')); ?>">
        <small><?php echo $this->lmsg('api-key') ?></small>
        <h4><?php echo $this->token; ?>
        <button type="submit" class="btn btn-xs">Generate New API Key</button></h4>
    </form>

        <small>Webhook Endpoint</small>
        <h4><?php echo $entryPoint; ?></h4>
</section>

<h3><?php echo $this->lmsg('add-action') ?></h3>
<section>
    <form class="form-inline" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'addAction')); ?>" method="post">
        <table>
            <thead>
            <tr>
                <td>
                    <small>Event</small>
                    <br/>
                    <select name="event">
                        <option value="*">All Events</option>
                        <option value="tag_test">User is sending Spam</option>
                        <option>User is sending to invalid recipients</option>
                        <option>User is generating complaints from receivers</option>
                    </select>
                </td>
                <td>
                    <small>Action</small>
                    <br/>
                    <select name="action">
                        <!--
                                    <option>Throttle Sender</option>
                                    <option>Throttle Domain</option>
                                    <option>Block Sender</option>
                        -->
                        <option>Block Domain</option>
                    </select>
                </td>
                <td>
                    <button class="btn btn-default btn-xs">Add Action</button>
                </td>
            </thead>

            <?php

            foreach ($this->actionConfig as $item) {
                echo "<tr>";
                echo sprintf("<td>%s</td><td>%s</td>", $item['event'], $item['action']);
                echo "</tr>";
            }
            ?>
        </table>
    </form>
</section>
